# Generated by Django 4.0.4 on 2022-07-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0004_stages_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages',
            name='slug',
        ),
    ]
