# Generated by Django 4.0.4 on 2022-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0005_remove_stages_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stages',
            name='link',
        ),
        migrations.AddField(
            model_name='stages',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
