# Generated by Django 4.0.4 on 2022-07-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0008_alter_clients_options_alter_clients_status_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Статус по коврам',
                'verbose_name_plural': 'Статусы по коврам',
            },
        ),
    ]
