# Generated by Django 4.0.4 on 2022-07-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0009_matstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matstatus',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
