# Generated by Django 4.0.4 on 2022-07-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0010_alter_matstatus_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='status_sales',
            new_name='stage_status',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='status_competitors',
        ),
        migrations.AddField(
            model_name='clients',
            name='mat_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='my_crm.matstatus'),
        ),
    ]
