# Generated by Django 4.0.4 on 2022-07-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0011_rename_status_sales_clients_stage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
