# Generated by Django 4.0.4 on 2022-07-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0012_clients_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.CharField(max_length=10),
        ),
    ]
